basePath: /
definitions:
  models.AuthSwag:
    properties:
      captcha_code:
        type: string
      captcha_id:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  models.Reg:
    properties:
      captcha_code:
        type: string
      captcha_id:
        type: string
      password:
        type: string
      password_again:
        type: string
      username:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: zskjcn@qq.com
    name: zskj
    url: https://github.com/zskj
  description: Blog
  license: {}
  termsOfService: http://wikis.tech/
  title: Blog API
  version: "1.0"
paths:
  /api/v1/auth:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.AuthSwag'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: 用户登录 获取token 信息
      tags:
      - 用户管理
  /api/v1/currentuser:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 获取登录用户信息
      tags:
      - 用户管理
  /api/v1/pub/captcha:
    get:
      parameters:
      - description: 验证码ID
        in: query
        name: captchaId
        required: true
        type: string
      produces:
      - image/png
      responses:
        "200":
          description: 图形验证码
        "400":
          description: '{code:400,data:null,msg:无效的请求参数}'
          schema:
            type: string
      summary: 响应图形验证码
      tags:
      - 公共接口
  /api/v1/pub/captchaid:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 获取验证码信息
      tags:
      - 公共接口
  /api/v1/refreshtoken:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 刷新token
      tags:
      - 用户管理
  /api/v1/reg:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/models.Reg'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
      summary: 注册用户
      tags:
      - 用户管理
  /api/v1/tags:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 文章标签列表
      tags:
      - 标签管理
    post:
      parameters:
      - description: Name
        in: query
        name: name
        required: true
        type: string
      - description: State
        in: query
        name: state
        type: integer
      - description: CreatedBy
        in: query
        name: created_by
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 新增文章标签
      tags:
      - 标签管理
  /api/v1/tags/{id}:
    delete:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 删除文章标签
      tags:
      - 标签管理
    put:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: Name
        in: query
        name: name
        required: true
        type: string
      - description: State
        in: query
        name: state
        type: integer
      - description: ModifiedBy
        in: query
        name: modified_by
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 编辑文章标签
      tags:
      - 标签管理
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
